language: ruby
sudo: false
cache: bundler
before_script:
  - npm install --silent
  - cp config/application.sample.yml config/application.yml
  - cp config/database.sample.yml config/database.yml
  - psql -c 'create database rails_assets_test;' -U postgres
  - bundle exec rake db:migrate
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bundle exec rspec
services:
  - redis-server
rvm:
  - 2.2.3
