default: &default
  adapter: postgresql
  username: rails_assets
  password:
  pool: 30
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: rails_assets_development

test:
  <<: *default
  database: rails_assets_test

staging:
  <<: *default
  database: rails_assets_staging

production:
  <<: *default
  database: rails_assets_production
