development:
  adapter: postgresql
  encoding: unicode
  database: rails_assets_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rails_assets_test
  pool: 5
  username: postgres
  password:
