development:
  adapter: postgresql
  encoding: unicode
  database: rails_assets_development
  pool: 30
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rails_assets_test
  pool: 30
  password:
